// Generated by the ${WOLipsContext.getPluginName()} at ${Date}
package $componentsPackage;

import org.treasureboat.webcore.components.TBComponent;
import com.webobjects.appserver.WOContext;

public class Main extends TBComponent {
	private static final long serialVersionUID = 1L;

	public Main(WOContext context) {
		super(context);
	}
}
