// Generated by the ${WOLipsContext.getPluginName()} at ${Date}
package $basePackage;

import er.extensions.appserver.TBApplication;

public class Application extends TBApplication {
	public static void main(String[] argv) {
		TBApplication.main(argv, Application.class);
	}

	public Application() {
	    super();
	    log.info("=================================================");
	    log.info("Welcome to " + name() + " !");
	    log.info("=================================================");
	  	
	    /* ** put your initialization code in here ** */
	}
}
