// Generated by the ${WOLipsContext.getPluginName()} at ${Date}
package $basePackage;

import org.treasureboat.webcore.appserver.TBSession;

public class Session extends TBSession {
	private static final long serialVersionUID = 1L;

	public Session() {
	}
}
